name: tomopy
channels:
  - astra-toolbox
  - conda-forge
  - defaults
dependencies:
  - astra-toolbox
  - dxchange
  - python
  # We don't need the full matplotlib with QT because we are using jupyter
  - matplotlib-base
  # astra-toolbox has not released stable builds with Python > 3.6
  - python=3.6
  - tomopy
